_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.13
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
batch_size:
    value: 8
learning_rate:
    value: 1e-05
lora_alpha:
    value: 16
lora_dropout:
    value: 0.1
lora_rank:
    value: 8
num_epochs:
    value: 3
warmup_steps:
    value: 500
weight_decay:
    value: 0.01
